services:
    alist:
        image: 'xhofe/alist:latest'
        container_name: alist
        volumes:
            - '/usr/local/emby-cloud/alist:/opt/alist/data'
        ports:
            - '5244:5244'
        environment:
            - PUID=0
            - PGID=0
            - UMASK=022
        restart: unless-stopped