services:
  ddns-go:
    image: jeessy/ddns-go
    container_name: ddns-go
    restart: always
    network_mode: host
    volumes:
      - "D:/OneDrive - MSFT/docker-data/ddns/data:/root/data"
    environment:
      - TZ=Asia/Shanghai